# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build XZ Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-xz*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/xz*.Dockerfile"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-xz*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/xz*.Dockerfile"

jobs:
  build-utils-dockerfile:
    name: Build XZ Dockerfile
    uses: robomics/compress-nfcore-hic-output/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/xz*.Dockerfile"

    permissions:
      contents: read
      packages: write
